name: Build and Release linux x86_64

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Exécution chaque dimanche à minuit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Linux - Get latest FFmpeg release
        id: ffmpeg
        run: |
          FFmpeg_RELEASE_URL="https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest"
          FFmpeg_ASSET_URL=$(curl -sL $FFmpeg_RELEASE_URL | jq -r '.assets[] | select(.name | contains("linux64-lgpl-8.1.tar.xz")) | .browser_download_url')
          echo "ffmpeg_asset_url=$FFmpeg_ASSET_URL" >> $GITHUB_ENV
          echo "ffmpeg_version=$(curl -sL $FFmpeg_RELEASE_URL | jq -r '.tag_name')" >> $GITHUB_ENV

      - name: Linux - Get latest uv release
        id: uv
        run: |
          UV_RELEASE_URL="https://api.github.com/repos/astral-sh/uv/releases/latest"
          UV_ASSET_URL=$(curl -sL $UV_RELEASE_URL | jq -r '.assets[] | select(.name | test("x86_64-unknown-linux-gnu.tar.gz$")) | .browser_download_url')
          echo "uv_asset_url=$UV_ASSET_URL" >> $GITHUB_ENV
          echo "uv_version=$(curl -sL $UV_RELEASE_URL | jq -r '.tag_name')" >> $GITHUB_ENV

      - name: Linux - Download and extract FFmpeg
        run: |
          curl -L -o ffmpeg.tar.xz ${{ env.ffmpeg_asset_url }}
          mkdir -p ffmpeg_extracted
          tar -xf ffmpeg.tar.xz -C ffmpeg_extracted --strip-components=1

      - name: Linux - Download and extract uv
        run: |
          curl -L -o uv.tar.gz ${{ env.uv_asset_url }}
          mkdir -p uv_extracted
          tar -xf uv.tar.gz -C uv_extracted --strip-components=1

      - name: Linux - Create combined release structure
        run: |
          # Copier les binaires
          cp -r ffmpeg_extracted/bin/ffmpeg ./
          cp -r uv_extracted/uv ./
          rm -rf ffmpeg_extracted uv_extracted ffmpeg.tar.xz uv.tar.gz
          # Rendre les binaires exécutables
          chmod +x ./ffmpeg
          chmod +x ./uv
          ls -l

      - name: Linux - Create combined archive
        run: |
          touch release.tar.gz
          tar --exclude=release.tar.gz -czf release.tar.gz .

      - name: Windows - Get latest FFmpeg release
        id: ffmpeg
        run: |
          FFmpeg_RELEASE_URL="https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest"
          FFmpeg_ASSET_URL=$(curl -sL $FFmpeg_RELEASE_URL | jq -r '.assets[] | select(.name | contains("win64-lgpl-8.1.zip")) | .browser_download_url')
          echo "ffmpeg_asset_url=$FFmpeg_ASSET_URL" >> $GITHUB_ENV
          echo "ffmpeg_version=$(curl -sL $FFmpeg_RELEASE_URL | jq -r '.tag_name')" >> $GITHUB_ENV

      - name: Windows - Get latest uv release
        id: uv
        run: |
          UV_RELEASE_URL="https://api.github.com/repos/astral-sh/uv/releases/latest"
          UV_ASSET_URL=$(curl -sL $UV_RELEASE_URL | jq -r '.assets[] | select(.name | test("x86_64-pc-windows-msvc.zip$")) | .browser_download_url')
          echo "uv_asset_url=$UV_ASSET_URL" >> $GITHUB_ENV
          echo "uv_version=$(curl -sL $UV_RELEASE_URL | jq -r '.tag_name')" >> $GITHUB_ENV

      - name: Windows - Download and extract FFmpeg
        run: |
          curl -L -o ffmpeg.zip ${{ env.ffmpeg_asset_url }}
          mkdir -p ffmpeg_extracted
          unzip ffmpeg.zip -d ffmpeg_extracted

      - name: Windows - Download and extract uv
        run: |
          curl -L -o uv.zip ${{ env.uv_asset_url }}
          mkdir -p uv_extracted
          tunzip uv.zip -d uv_extracted

      - name: Windows - Create combined release structure
        run: |
          mkdir -p release
          # Copier les binaires
          cp -r ffmpeg_extracted/bin/ffmpeg.exe ./
          cp -r uv_extracted/uv.exe ./
          rm -rf ffmpeg_extracted uv_extracted ffmpeg.zip uv.zip
          ls -l

      - name: Windows - Create combined archive
        run: |
          zip release.zip .

      - name: Upload combined archive
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.ffmpeg_version }}-${{ env.uv_version }}
          name: Release ${{ env.ffmpeg_version }}-${{ env.uv_version }}
          body: |
            Release containing:
            - FFmpeg version: ${{ env.ffmpeg_version }}
            - uv version: ${{ env.uv_version }}
            
            Binaries included:
            - ffmpeg
            - uv
            
            Source code: Included in the archive
          files: |
            ./release.tar.gz
            ./release.zip
          prerelease: true
          draft: true

      - name: Cleanup
        run: |
          rm -rf ffmpeg_extracted uv_extracted release release.tar.gz
